version: '3'
services:
  mysql:
    image: mysql:5.7.12
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - TZ=UTC
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/var/log
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./configs/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    container_name: mysql
